name: "demo"
task: "t2i"
prompt_path: "data/dataset/prompts/trim_t2i.json"

generation:
    models: ["dalle3",]
    output_dir: ["data/output/dalle",]

evaluation:
    image_dir: ["data/output/demo",]
    result_dir: "data/result"

dimensions:
    IQ-O:
        metrics: ["GPTLogitMetric"]
    TA-R:
        metrics: ["GPTLogitMetric"]
    TA-S:
        metrics: ["GPTLogitMetric", "AnotherMetric"]
