name: "demo_eval"
task: "t2i"
prompt_path: "/home/muzammal/Projects/TRIG/dataset/Trig/Trig-text-to-image/text-to-imgae-without-m-e-v8.json"

evaluation:
    image_dirs: ["/home/muzammal/Projects/TRIG/data/output/t2i/demo"]
    result_dir: "data/result"
    result_files: ["data/result/demo2.json"]

TRIG_metric_72B: &TRIG_metric_72B
  name: trig_api
  endpoint: "http://localhost:10021/v1/"
  model_name: Benasd/Qwen2.5-VL-72B-Instruct-AWQ
  top_logprobs: 5

dimensions:
  TA-R:
    metrics:
      - <<: *TRIG_metric_72B
  IQ-O:
    metrics:
      - <<: *TRIG_metric_72B
  TA-S:
    metrics:
      - <<: *TRIG_metric_72B
