name: "demo"
task: "t2i"

generation:
    run: True
    model: "dalle3"
    prompt_file: "data/dataset/prompts/trim_t2i.json"

evaluation:
    run: True
    image_dir: "data/output/demo"
    result_dir: "data/result"

dimensions:
    IQ-O:
        metrics: ["BaseMetric", "GPTLogitMetric"]
    TA-R:
        metrics: ["BaseMetric"]
    TA-S:
        metrics: ["GPTLogitMetric", "AnotherMetric"]
