name: "flux"
task: "t2i"
prompt_path: "/home/muzammal/Projects/TRIG/dataset/Trig/Trig-text-to-image/text-to-imgae-without-m-e-v8.json"

evaluation:
    image_dirs: ["/home/muzammal/Projects/TRIG/data/output/t2i/flux"]
    result_dir: "data/result"
    result_files: ["data/result/flux_GPT_t1.json"]

TRIG_metric: &TRIG_metric
  name: trig_api
  model_name: Qwen/Qwen2.5-VL-7B-Instruct
  endpoint: "http://localhost:8001/v1/"
  top_logprobs: 5

TRIG_metric_72B: &TRIG_metric_72B
  name: trig_api
  API_KEY: "sk-3816bf9e709540598d239fc684fe0423"
  endpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1/"
  model_name: qwen2.5-vl-72b-instruct
  top_logprobs: 5

TRIG_metric_GPT: &TRIG_metric_GPT
  name: trig_api
  API_KEY: "sk-mqUwZI8bhIv746rG6f3fE830D8B146E789Fd11717aD8C4B1"
  endpoint: "https://api.bltcy.ai/v1"
  model_name: gpt-4o
  top_logprobs: 5

dimensions:
  IQ-R:
    metrics:
      - <<: *TRIG_metric_72B
  IQ-O:
    metrics:
      - <<: *TRIG_metric_72B
  IQ-A:
    metrics:
      - <<: *TRIG_metric_72B
  TA-R:
    metrics:
      - <<: *TRIG_metric_72B
  TA-C:
    metrics:
      - <<: *TRIG_metric_72B
  TA-S:
    metrics:
      - <<: *TRIG_metric_72B
  D-K:
    metrics:
      - <<: *TRIG_metric_72B
  D-A:
    metrics:
      - <<: *TRIG_metric_72B
  R-T:
    metrics:
      - <<: *TRIG_metric_72B
  R-B:  
    metrics:
      - <<: *TRIG_metric_72B
