name: "flux"
task: "t2i"
prompt_path: "/home/muzammal/Projects/TRIG/dataset/Trig/Trig-text-to-image/text-to-imgae-without-m-e-v8.json"

evaluation:
    image_dirs: ["/home/muzammal/Projects/TRIG/data/output/t2i/flux", "/home/muzammal/Projects/TRIG/data/output/t2i/janus"]
    result_dir: "data/result"
    result_files: ["data/result/flux_llava_7B_t1.json", "data/result/janus_llava_7B_t1.json"]

TRIG_metric: &TRIG_metric
  name: trig_api
  model_name: Qwen/Qwen2.5-VL-7B-Instruct
  endpoint: "http://localhost:8001/v1/"
  top_logprobs: 5

TRIG_metric_72B: &TRIG_metric_72B
  name: trig_api
  endpoint: "http://localhost:8000/v1/"
  model_name: PointerHQ/Qwen2.5-VL-72B-Instruct-Pointer-AWQ
  top_logprobs: 5

TRIG_metric_GPT: &TRIG_metric_GPT
  name: trig_api
  API_KEY: "sk-mqUwZI8bhIv746rG6f3fE830D8B146E789Fd11717aD8C4B1"
  endpoint: "https://api.bltcy.ai/v1"
  model_name: gpt-4o
  top_logprobs: 5

TRIG_metric_llava: &TRIG_metric_llava
  name: trig_api
  endpoint: "http://localhost:10022/v1/"
  model_name: llava-hf/llava-onevision-qwen2-7b-ov-hf
  top_logprobs: 5

dimensions:
  IQ-R:
    metrics:
      - <<: *TRIG_metric_llava
  IQ-O:
    metrics:
      - <<: *TRIG_metric_llava
  IQ-A:
    metrics:
      - <<: *TRIG_metric_llava
  TA-R:
    metrics:
      - <<: *TRIG_metric_llava
  TA-C:
    metrics:
      - <<: *TRIG_metric_llava
  TA-S:
    metrics:
      - <<: *TRIG_metric_llava
  D-K:
    metrics:
      - <<: *TRIG_metric_llava
  D-A:
    metrics:
      - <<: *TRIG_metric_llava
  R-T:
    metrics:
      - <<: *TRIG_metric_llava
  R-B:  
    metrics:
      - <<: *TRIG_metric_llava
