name: "sdxl"
task: "t2i"
prompt_path: "/home/muzammal/Projects/TRIG/dataset/Trig/Trig-text-to-image/text-to-imgae-without-m-e-v8.json"

evaluation:
    image_dirs: ["/home/muzammal/Projects/TRIG/data/output/t2i/sdxl",]
    result_dir: "data/result"
    result_files: ["data/result/t2i/sdxl_qwen_72B_t1.json", ]

TRIG_metric: &TRIG_metric
  name: trig_api
  model_name: Qwen/Qwen2.5-VL-7B-Instruct
  endpoint: "http://localhost:10021/v1/"
  top_logprobs: 5

TRIG_metric_72B: &TRIG_metric_72B
  name: trig_api
  endpoint: "http://localhost:8000/v1/"
  model_name: Qwen/Qwen2-VL-72B-Instruct-AWQ
  top_logprobs: 5

TRIG_metric_GPT: &TRIG_metric_GPT
  name: trig_api
  API_KEY: "sk-mqUwZI8bhIv746rG6f3fE830D8B146E789Fd11717aD8C4B1"
  endpoint: "https://api.bltcy.ai/v1"
  model_name: gpt-4o
  top_logprobs: 5

TRIG_metric_llava: &TRIG_metric_llava
  name: trig_api
  endpoint: "http://localhost:10022/v1/"
  model_name: llava-hf/llava-onevision-qwen2-7b-ov-hf
  top_logprobs: 5

dimensions:
  IQ-R:
    metrics:
      - <<: *TRIG_metric_72B
  IQ-O:
    metrics:
      - <<: *TRIG_metric_72B
  IQ-A:
    metrics:
      - <<: *TRIG_metric_72B
  TA-R:
    metrics:
      - <<: *TRIG_metric_72B
  TA-C:
    metrics:
      - <<: *TRIG_metric_72B
  TA-S:
    metrics:
      - <<: *TRIG_metric_72B
  D-K:
    metrics:
      - <<: *TRIG_metric_72B
  D-A:
    metrics:
      - <<: *TRIG_metric_72B
  R-T:
    metrics:
      - <<: *TRIG_metric_72B
  R-B:  
    metrics:
      - <<: *TRIG_metric_72B
