name: "flux"
task: "t2i"
prompt_path: "/home/muzammal/Projects/TRIG/dataset/Trig/Trig-text-to-image/text-to-imgae-without-m-e-v8.json"

evaluation:
    image_dirs: ["/home/muzammal/Projects/TRIG/data/output/t2i/flux", "/home/muzammal/Projects/TRIG/data/output/t2i/janus", "/home/muzammal/Projects/TRIG/data/output/t2i/omnigen"]
    result_dir: "data/result"
    result_files: ["data/result/flux_7B_t1.json", "data/result/janus_7B_t1.json", "data/result/omnigen_7B_t1.json"]

TRIG_metric: &TRIG_metric
  name: trig_api
  model_name: Qwen/Qwen2.5-VL-7B-Instruct
  top_logprobs: 5

TRIG_metric_72B: &TRIG_metric_72B
  name: trig_api
  endpoint: "http://localhost:10021/v1/"
  model_name: Benasd/Qwen2.5-VL-72B-Instruct-AWQ
  top_logprobs: 5

dimensions:
  IQ-R:
    metrics:
      - <<: *TRIG_metric
  IQ-O:
    metrics:
      - <<: *TRIG_metric
  IQ-A:
    metrics:
      - <<: *TRIG_metric
  TA-R:
    metrics:
      - <<: *TRIG_metric
  TA-C:
    metrics:
      - <<: *TRIG_metric
  TA-S:
    metrics:
      - <<: *TRIG_metric
  D-K:
    metrics:
      - <<: *TRIG_metric
  D-A:
    metrics:
      - <<: *TRIG_metric
  R-T:
    metrics:
      - <<: *TRIG_metric
  R-B:  
    metrics:
      - <<: *TRIG_metric
