name: "flux"
task: "t2i"
prompt_path: "/home/muzammal/Projects/TRIG/dataset/Trig/Trig-text-to-image/text-to-imgae-without-m-e-v8.json"

evaluation:
    image_dirs: ["/home/muzammal/Projects/TRIG/data/output/t2i/flux",]
    result_dir: "data/result"
    result_files: ["data/result/flux_gpt_t1.json", ]

TRIG_metric: &TRIG_metric
  name: trig_api
  model_name: Qwen/Qwen2.5-VL-7B-Instruct
  top_logprobs: 5

TRIG_metric_72B: &TRIG_metric_72B
  name: trig_api
  endpoint: "http://localhost:10021/v1/"
  model_name: Benasd/Qwen2.5-VL-72B-Instruct-AWQ
  top_logprobs: 5

TRIG_metric_gpt: &TRIG_metric_gpt
  name: trig_api
  API_KEY: "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"
  endpoint: "https://api.openai.com/v1/"
  model_name: "gpt-4o"
  top_logprobs: 5

dimensions:
  IQ-R:
    metrics:
      - <<: *TRIG_metric_gpt
  IQ-O:
    metrics:
      - <<: *TRIG_metric_gpt
  IQ-A:
    metrics:
      - <<: *TRIG_metric_gpt
  TA-R:
    metrics:
      - <<: *TRIG_metric_gpt
  TA-C:
    metrics:
      - <<: *TRIG_metric_gpt
  TA-S:
    metrics:
      - <<: *TRIG_metric_gpt
  D-K:
    metrics:
      - <<: *TRIG_metric_gpt
  D-A:
    metrics:
      - <<: *TRIG_metric_gpt
  R-T:
    metrics:
      - <<: *TRIG_metric_gpt
  R-B:  
    metrics:
      - <<: *TRIG_metric_gpt
