name: "test"
task: "t2i"
prompt_path: "/home/zsc/TRIG/dataset/Trig/Trig-text-to-image/text-to-imgae-without-m-e-v7.json"

generation:
    # all models: ["base", "dalle3", "sdxl", "omnigen", "pixart_sigma", "onediffusion", "sana", "sd35", 'flux']
    models: ["sana",]