name: "relation" # name for this experiment
task: "t2i" # chosen from t2i/p2p/sub, Support one task at a time
# json path for the selected task

relation:
  models: ["test"]
  res: "demo"
  metric: "pearson_corr"  # [pearson_corr, spearman_corr, paretoF]
  plot: true  # Set to true to generate scatter plots
  heatmap: true
  tsne: true
  tradeoff: true  # Enable trade-off analysis
  node_colors:  # Optional: specify colors for specific metrics
    "IQ-O": "#ff7f0e"  # Orange
    "TA-R": "#1f77b4"  # Blue
    "TA-S": "#2ca02c"  # Green