# python eval.py --config config/relation.yaml

name: "relation"
task: "t2i"
relation:
  models: ["flux"]
  res: "formatted_flux"
  metric: "spearman_corr"  # 可选值: pearson_corr, spearman_corr, paretoF
  plot: true
  heatmap: true
  tsne: true
  tradeoff: true
  quadrant_analysis: true
  thresholds:
    synergy: 0.8      # 协同区阈值
    bottleneck: 0.5   # 瓶颈区阈值
    
  insight_thresholds:
    synergy_density: 0.4    # 协同区密度阈值
    bottleneck_density: 0.4 # 瓶颈区密度阈值
    dominance_ratio: 0.8    # 主导比例阈值（0.5表示比例阈值为2）
    tradeoff_corr: 0.6      # 零和博弈判定的相关系数阈值