evaluation:
    name: "demo"
    model: "dalle3"
    task: "t2i"
    image_dir: "data\output\demo"
    result_dir: "data\result"

API_KEY: ""

dimensions:
    IQ-O:
      name: "Content"
      module: "metrics.gpt_logit"
      class: "GPTLogitMetric"
      params: {}
    TA-R:
      name: "Content"
      module: "metrics.gpt_logit"
      class: "GPTLogitMetric"
      params: {}
    TA-S:
      name: "Content"
      module: "metrics.gpt_logit"
      class: "GPTLogitMetric"
      params: {}